import numpy as np

data = np.array(['sami', 'maaj', 'malhar', 'atharv'])
zeros = np.zeros((2, 2))
ones = np.ones((3, 3))
identity = np.eye(4)
arange = np.arange(10)
linspace = np.linspace(0, 1, 5)
random = np.random.random((2, 2))
randint = np.random.randint(10, size=(3, 3))
reshaped = np.reshape(arange, (2, 5))
transposed = np.transpose(linspace)
concatenated = np.concatenate((reshaped, reshaped), axis=0)
split = np.split(arange, 2)
mean = np.mean(arange)
std = np.std(linspace)
summed = np.sum(concatenated)
dot_product = np.dot(np.array([1, 2]), np.array([3, 4]))
inverse = np.linalg.inv(np.eye(3))
determinant = np.linalg.det(np.eye(3))
eigenvalues = np.linalg.eig(np.eye(3))
sine = np.sin(np.pi / 2)
cosine = np.cos(np.pi / 2)
tangent = np.tan(np.pi / 4)
exponential = np.exp(1)
logarithm = np.log(np.e)
sqrt = np.sqrt(16)
power = np.power(2, 3)
maximum = np.max(np.array([1, 2, 3]))
minimum = np.min(np.array([1, 2, 3]))